"""
OS control tools - each function is exposed to the LangGraph agent as a tool.
Windows-specific (uses os.startfile, ctypes user32, pycaw, dynamic app discovery).
"""
import ctypes
import os
import re
import shlex
import subprocess
import time
import webbrowser
import psutil

from langchain_core.tools import tool

from agent.tools.app_index import find_app_path

# Only keep entries here that need special handling:
# - launch arguments (like Valorant)
# - a friendlier alias than the actual exe/shortcut/registry name
# - a URI scheme handler (like ms-settings:) that the dynamic scanner can't discover
# - anything the dynamic index (registry + Start Menu scan) doesn't resolve correctly,
#   kept here so it launches instantly instead of going through the slower fallback
APP_MAP = {
    "settings": "start ms-settings:",
    "file explorer": "explorer",
    "explorer": "explorer",
    "task manager": "taskmgr",
    "calculator": "calc",
    "spotify": "start spotify",
    "discord": r"explorer.exe shell:AppsFolder\com.squirrel.Discord.Discord",
    "whatsapp": r"explorer.exe shell:AppsFolder\5319275A.WhatsAppDesktop_cv1g1gvanyjgm!App",
    "valorant": r"explorer.exe shell:AppsFolder\Microsoft.AutoGenerated.{B90C4CF3-5116-AEB7-2542-2440C94B666D}"
}

# Never allow close_application to touch these - either core Windows processes
# whose death can crash/hang the OS, or Aria's own process.
PROTECTED_PROCESSES = {
    "explorer", "csrss", "wininit", "winlogon", "services", "lsass",
    "svchost", "dwm", "smss", "system", "registry",
    "python", "pythonw",  # Aria itself runs on these - don't let it self-terminate
}


def _normalize(name: str) -> str:
    """Collapses hyphens/underscores to spaces, strips punctuation, lowercases."""
    name = re.sub(r"[-_]+", " ", name)
    name = re.sub(r"[^\w\s]", "", name)
    return re.sub(r"\s+", " ", name).strip().lower()


def _split_exe_and_args(command: str):
    """Splits 'C:\\path with spaces\\App.exe --flag=value' into (exe_path, [args])."""
    match = re.search(r"^(.*?\.exe)\s*(.*)$", command, re.IGNORECASE)
    if match:
        exe_path = match.group(1).strip().strip('"')
        args_str = match.group(2).strip()
        args = shlex.split(args_str, posix=False) if args_str else []
        return exe_path, args
    return command, []


def _resolve_command(app_name: str):
    """Resolves a spoken app name to a launchable command, in priority order:
    1. Manual APP_MAP overrides (exact, then partial match)
    2. Dynamically discovered app index (registry + Start Menu scan)
    Returns (command, found) - found=False means nothing matched and the caller
    should fall back to raw-name + 'start' attempts with process verification.
    """
    key = _normalize(app_name)

    command = APP_MAP.get(key)
    if command is None:
        for map_key, map_cmd in APP_MAP.items():
            if map_key in key or key in map_key:
                command = map_cmd
                break
    if command is not None:
        return command, True

    command = find_app_path(key)
    if command is not None:
        return command, True

    return key, False


def _launch(command: str):
    """Fires off a launch attempt. Never raises on a bad command - shell=True
    'succeeds' (spawns cmd.exe) even when the underlying command is invalid,
    which is why success has to be verified separately via process checking."""
    try:
        if "\\" in command or ".exe" in command.lower():
            exe_path, args = _split_exe_and_args(command)
            subprocess.Popen([exe_path, *args])
        else:
            subprocess.Popen(command, shell=True)
    except Exception:
        pass


def _snapshot_process_names() -> set:
    names = set()
    for proc in psutil.process_iter(["name"]):
        try:
            name = proc.info["name"] or ""
            names.add(_normalize(os.path.splitext(name)[0]))
        except (psutil.NoSuchProcess, psutil.AccessDenied):
            continue
    return names


def _new_matching_process_appeared(key: str, before: set, timeout: float = 2.0, poll: float = 0.3) -> bool:
    """Polls for up to `timeout` seconds for a NEW process (not in `before`) whose
    name matches `key`. This is how we detect launch success, since shell=True
    'succeeds' even when the underlying command is invalid."""
    elapsed = 0.0
    while elapsed < timeout:
        time.sleep(poll)
        elapsed += poll
        new_names = _snapshot_process_names() - before
        if any(key in name or name in key for name in new_names if name):
            return True
    return False


@tool
def open_application(app_name: str) -> str:
    """Opens a desktop application by name, e.g. 'chrome', 'notepad', 'vs code', 'calculator', 'valorant'."""
    command, found = _resolve_command(app_name)

    if found:
        # Resolved via APP_MAP or the dynamic registry/Start Menu index - trust it,
        # no need to slow things down with process-checking.
        _launch(command)
        return f"Opening {app_name}."

    # Nothing resolved. Try the raw name first, then fall back to Windows' "start"
    # command - "start" additionally resolves App Paths, URI protocol handlers, and
    # Store app monikers that our scanner sometimes misses.
    key = _normalize(app_name)
    before = _snapshot_process_names()

    _launch(key)
    if _new_matching_process_appeared(key, before):
        return f"Opening {app_name}."

    _launch(f'start "" {key}')
    if _new_matching_process_appeared(key, before, timeout=2.5):
        return f"Opening {app_name}."

    return (f"I couldn't find an app called '{app_name}'. "
            f"You may need to add it to APP_MAP in os_control.py.")


@tool
def close_application(app_name: str) -> str:
    """Force-closes a running application by its name, e.g. 'chrome', 'notepad', 'calculator'."""
    key = _normalize(app_name)

    if key in PROTECTED_PROCESSES:
        return f"I won't close {app_name} - it's a protected system process."

    exact_matches = []
    fuzzy_matches = []

    for proc in psutil.process_iter(["pid", "name"]):
        try:
            proc_name = (proc.info["name"] or "")
            proc_key = _normalize(os.path.splitext(proc_name)[0])

            # Hard block regardless of match type - never touch these
            if proc_key in PROTECTED_PROCESSES:
                continue

            if proc_key == key:
                exact_matches.append((proc.info["pid"], proc_name))
            elif key in proc_key or proc_key in key:
                fuzzy_matches.append((proc.info["pid"], proc_name))

        except (psutil.NoSuchProcess, psutil.AccessDenied):
            continue

    # Prefer exact matches. Only fall back to fuzzy if nothing exact was found -
    # this avoids "chrome" fuzzy-matching five different helper processes when
    # the real chrome.exe process is right there as an exact match.
    matched = exact_matches if exact_matches else fuzzy_matches

    if not matched:
        return f"{app_name} doesn't seem to be running."

    matched_names = set()
    killed, failed = 0, 0
    for pid, name in matched:
        matched_names.add(name)
        try:
            psutil.Process(pid).terminate()
            killed += 1
        except (psutil.NoSuchProcess, psutil.AccessDenied):
            failed += 1

    if killed:
        return f"Closed {app_name} ({', '.join(matched_names)})."
    return f"Couldn't close {app_name} - access denied."


@tool
def lock_computer() -> str:
    """Locks the Windows computer immediately."""
    ctypes.windll.user32.LockWorkStation()
    return "Locking the computer."

# Tracks a shutdown request awaiting voice confirmation. Kept in-memory since
# Aria is a single-user desktop app - no need for persistence across restarts.
_pending_shutdown = {"minutes": None, "expires_at": None}
SHUTDOWN_CONFIRMATION_WINDOW = 15  # seconds to say "confirm shutdown" before it expires


@tool
def shutdown_computer(minutes: int = 0) -> str:
    """Requests a computer shutdown. Does NOT shut down immediately - the user
    must say 'confirm shutdown' within 15 seconds, otherwise the request expires."""
    global _pending_shutdown
    minutes = max(0, int(minutes))
    _pending_shutdown = {"minutes": minutes, "expires_at": time.time() + SHUTDOWN_CONFIRMATION_WINDOW}
    if minutes:
        return f"Are you sure you want to shut down in {minutes} minutes? Say 'confirm shutdown' to proceed."
    return "Are you sure you want to shut down now? Say 'confirm shutdown' to proceed."


@tool
def confirm_shutdown() -> str:
    """Confirms and executes a shutdown that was just requested. Only works within
    15 seconds of shutdown_computer being called - otherwise the request has expired."""
    global _pending_shutdown
    if not _pending_shutdown["expires_at"] or time.time() > _pending_shutdown["expires_at"]:
        _pending_shutdown = {"minutes": None, "expires_at": None}
        return "There's no pending shutdown request, or it expired. Ask to shut down again."

    minutes = _pending_shutdown["minutes"]
    seconds = minutes * 60
    subprocess.run(["shutdown", "/s", "/t", str(seconds)])
    _pending_shutdown = {"minutes": None, "expires_at": None}

    if minutes:
        return f"Confirmed. Shutting down in {minutes} minutes."
    return "Confirmed. Shutting down now."


@tool
def cancel_shutdown() -> str:
    """Cancels a previously scheduled or pending shutdown."""
    global _pending_shutdown
    _pending_shutdown = {"minutes": None, "expires_at": None}
    subprocess.run(["shutdown", "/a"])
    return "Shutdown cancelled."

@tool
def set_volume(level: int) -> str:
    """Sets the system volume to a percentage from 0 to 100."""
    try:
        from pycaw.pycaw import AudioUtilities

        level = max(0, min(100, int(level)))
        device = AudioUtilities.GetSpeakers()
        volume = device.EndpointVolume  # newer pycaw exposes this directly, no Activate() needed
        volume.SetMasterVolumeLevelScalar(level / 100, None)
        return f"Volume set to {level}%."
    except Exception as e:
        return f"Couldn't change volume: {type(e).__name__}: {e}"


@tool
def search_web(query: str) -> str:
    """Opens the default browser and searches Google for the given query."""
    webbrowser.open(f"https://www.google.com/search?q={query}")
    return f"Searching the web for {query}."


@tool
def open_file_or_folder(path: str) -> str:
    """Opens a file or folder at the given path using the default Windows program."""
    try:
        os.startfile(path)
        return f"Opening {path}."
    except Exception as e:
        return f"Couldn't open {path}: {e}"


ALL_OS_TOOLS = [
    open_application,
    close_application,
    lock_computer,
    shutdown_computer,
    confirm_shutdown,
    cancel_shutdown,
    set_volume,
    search_web,
    open_file_or_folder,
]